// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCard(arg1, arg2) {
  return window['go']['service']['CardService']['CreateCard'](arg1, arg2);
}

export function DeleteCard(arg1) {
  return window['go']['service']['CardService']['DeleteCard'](arg1);
}

export function GetCard(arg1) {
  return window['go']['service']['CardService']['GetCard'](arg1);
}

export function ListCards() {
  return window['go']['service']['CardService']['ListCards']();
}

export function ReadCardsByDeck(arg1) {
  return window['go']['service']['CardService']['ReadCardsByDeck'](arg1);
}
