// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';

export function CreateCard(arg1:string,arg2:string):Promise<entity.Card>;

export function DeleteCard(arg1:number):Promise<void>;

export function GetCard(arg1:number):Promise<entity.Card>;

export function ListCards():Promise<Array<entity.Card>>;

export function ReadCardsByDeck(arg1:number):Promise<Array<entity.Card>>;
