// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {model} from '../models';

export function AddCard(arg1:context.Context,arg2:number,arg3:model.Card):Promise<void>;

export function CreateDeck(arg1:context.Context,arg2:string,arg3:Array<model.Card>):Promise<model.Deck>;

export function Delete(arg1:context.Context,arg2:number):Promise<void>;

export function DeleteCard(arg1:context.Context,arg2:number,arg3:number):Promise<void>;

export function FindAllCards(arg1:context.Context,arg2:number):Promise<Array<model.Card>>;

export function FindById(arg1:context.Context,arg2:number):Promise<model.Deck>;

export function GetDecks(arg1:context.Context):Promise<Array<model.Deck>>;

export function Save(arg1:context.Context,arg2:model.Deck):Promise<void>;

export function Update(arg1:context.Context,arg2:number,arg3:string,arg4:Array<model.Card>,arg5:Array<string>):Promise<void>;

export function UpdateCard(arg1:context.Context,arg2:number,arg3:number,arg4:string,arg5:string):Promise<void>;
