// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';

export function CreateDeck(arg1:string):Promise<entity.Deck>;

export function DeleteDeck(arg1:number):Promise<void>;

export function GetDeck(arg1:number):Promise<entity.Deck>;

export function ListDecks():Promise<Array<entity.Deck>>;
