// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCard(arg1, arg2, arg3) {
  return window['go']['service']['DeckService']['AddCard'](arg1, arg2, arg3);
}

export function CreateDeck(arg1, arg2, arg3) {
  return window['go']['service']['DeckService']['CreateDeck'](arg1, arg2, arg3);
}

export function Delete(arg1, arg2) {
  return window['go']['service']['DeckService']['Delete'](arg1, arg2);
}

export function DeleteCard(arg1, arg2, arg3) {
  return window['go']['service']['DeckService']['DeleteCard'](arg1, arg2, arg3);
}

export function FindAllCards(arg1, arg2) {
  return window['go']['service']['DeckService']['FindAllCards'](arg1, arg2);
}

export function FindById(arg1, arg2) {
  return window['go']['service']['DeckService']['FindById'](arg1, arg2);
}

export function GetDecks(arg1) {
  return window['go']['service']['DeckService']['GetDecks'](arg1);
}

export function Save(arg1, arg2) {
  return window['go']['service']['DeckService']['Save'](arg1, arg2);
}

export function Update(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['service']['DeckService']['Update'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateCard(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['service']['DeckService']['UpdateCard'](arg1, arg2, arg3, arg4, arg5);
}
