// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCard(arg1, arg2) {
  return window['go']['service']['DeckService']['AddCard'](arg1, arg2);
}

export function CreateDeck(arg1, arg2) {
  return window['go']['service']['DeckService']['CreateDeck'](arg1, arg2);
}

export function Delete(arg1) {
  return window['go']['service']['DeckService']['Delete'](arg1);
}

export function DeleteCard(arg1, arg2) {
  return window['go']['service']['DeckService']['DeleteCard'](arg1, arg2);
}

export function FindAllCards(arg1) {
  return window['go']['service']['DeckService']['FindAllCards'](arg1);
}

export function FindById(arg1) {
  return window['go']['service']['DeckService']['FindById'](arg1);
}

export function GetDecks() {
  return window['go']['service']['DeckService']['GetDecks']();
}

export function Save(arg1) {
  return window['go']['service']['DeckService']['Save'](arg1);
}

export function UpdateCard(arg1, arg2, arg3, arg4) {
  return window['go']['service']['DeckService']['UpdateCard'](arg1, arg2, arg3, arg4);
}

export function UpdateDeck(arg1, arg2, arg3) {
  return window['go']['service']['DeckService']['UpdateDeck'](arg1, arg2, arg3);
}
