// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {context} from '../models';

export function AddCard(arg1:number,arg2:model.Card):Promise<void>;

export function CreateDeck(arg1:string,arg2:Array<model.Card>):Promise<model.Deck>;

export function Delete(arg1:number):Promise<void>;

export function DeleteCard(arg1:number,arg2:number):Promise<void>;

export function FindAllCards(arg1:number):Promise<Array<model.Card>>;

export function FindById(arg1:context.Context,arg2:number):Promise<model.Deck>;

export function GetDecks():Promise<Array<model.Deck>>;

export function Save(arg1:model.Deck):Promise<void>;

export function Update(arg1:context.Context,arg2:number,arg3:string,arg4:Array<model.Card>,arg5:Array<string>):Promise<void>;

export function UpdateCard(arg1:number,arg2:number,arg3:string,arg4:string):Promise<void>;
