// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDeck(arg1) {
  return window['go']['service']['DeckService']['CreateDeck'](arg1);
}

export function DeleteDeck(arg1) {
  return window['go']['service']['DeckService']['DeleteDeck'](arg1);
}

export function GetDeck(arg1) {
  return window['go']['service']['DeckService']['GetDeck'](arg1);
}

export function ListDecks() {
  return window['go']['service']['DeckService']['ListDecks']();
}
