// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDeck(arg1) {
  return window['go']['application']['Factory']['CreateDeck'](arg1);
}

export function DeleteDeck(arg1) {
  return window['go']['application']['Factory']['DeleteDeck'](arg1);
}

export function GetAllDecks() {
  return window['go']['application']['Factory']['GetAllDecks']();
}

export function GetCards(arg1) {
  return window['go']['application']['Factory']['GetCards'](arg1);
}

export function NewCreateDeckInput(arg1, arg2) {
  return window['go']['application']['Factory']['NewCreateDeckInput'](arg1, arg2);
}

export function NewUpdateCardInput(arg1, arg2, arg3, arg4) {
  return window['go']['application']['Factory']['NewUpdateCardInput'](arg1, arg2, arg3, arg4);
}

export function NewUpdateInput(arg1, arg2, arg3, arg4) {
  return window['go']['application']['Factory']['NewUpdateInput'](arg1, arg2, arg3, arg4);
}

export function UpdateDeck(arg1) {
  return window['go']['application']['Factory']['UpdateDeck'](arg1);
}
