// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {deck} from '../models';

export function CreateDeck(arg1:any):Promise<any>;

export function GetAllDecks():Promise<any>;

export function GetCards(arg1:number):Promise<any>;

export function NewCreateDeckInput(arg1:string,arg2:Array<model.Card>):Promise<deck.CreateInput>;

export function NewUpdateCardInput(arg1:number,arg2:string,arg3:string,arg4:string):Promise<deck.UpdateCardInput>;

export function NewUpdateInput(arg1:number,arg2:string,arg3:number,arg4:Array<deck.UpdateCardInput>):Promise<deck.UpdateInput>;

export function UpdateDeck(arg1:any):Promise<any>;
